---
# ansible bug [https://github.com/ansible/ansible/issues/15443]
# ./manage.py fail with permission error due to manage.py is not executable
# so we use second version without django_migrate till bug fix

#- name: migrate
#  django_manage: >
#    command=migrate
#    app_path={{project_root}}



# Due permission issue this command failed with error:
# fatal: [default]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput", "failed": true, "msg": "[Errno 13] Permission denied", "rc": 13}
#
#- name: Run Django database migrations
#  django_manage:
#    command: migrate
#    app_path: "{{ project_root }}"
#    virtualenv: "{{ virtualenv }}"

- name: Run Django database migration
  shell: "source {{ virtualenv }}/bin/activate && python manage.py migrate"
  args:
    chdir: "{{ project_root }}"
    executable: /bin/bash